# Generated by Django 4.2.10 on 2024-02-14 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'unique_together': {('district', 'state', 'pincode')},
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('ownership', models.CharField(choices=[('JOINT', 'JOINT'), ('INDIVIDUAL', 'INDIVIDUAL')], default='INDIVIDUAL', max_length=10)),
                ('govt_id', models.CharField(choices=[('AADHAR', 'AADHAR'), ('VOTER_ID', 'VOTER_ID'), ('PAN', 'PAN'), ('PASSPORT', 'PASSPORT')], default='AADHAR', max_length=10)),
                ('govt_id_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('Commerical', 'Commerical'), ('Residential', 'Residential')], default='Residential', max_length=11)),
                ('load', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Connection Released', 'Connection Released')], default='Pending', max_length=20)),
                ('comment', models.TextField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='Connections.address')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='Connections.reviewer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
