# Generated by Django 4.2.10 on 2024-02-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0002_alter_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
